== Johdanto

[quote, Abelson &amp; Sussman, Structure and Interpretation of Computer Programs]
____
Thus, programs must be written for people to read, and only incidentally for machines to execute.
____

Suurin osa ohjelmointiteksteistä on suunnattu joko aloittelijoille, käsittelevät tiettyä teknologiaa tai yrittävät
opettaa jotain konkreettisia ohjelmointitekniikoita. Nämä ovat kaikki hyödyllisiä, mutta olen kaivannut sellaisia
kokeneille ohjelmoijille suunnattuja tekstejä, jotka keskittyisivät hienovaraisempiin asioihin: pohdiskelua tyylistä,
ylläpidettävyydestä, ilmaisukeinoista.

Olen siis kaivannut tekstejä ohjelmoijille, jotka eivät enää joudu käyttämään suurinta osaa ajastaan siihen miten
ongelma ratkaistaan teknisessä mielessä, vaan voivat keskittyä punniskelemaan erilaisten ilmaisutapojen hyviä ja
huonoja puolia.

Vertauksena voisi ottaa kirjoittamisen: suurin osa aikuisista ihmisistä ei joudu käyttämään energiaa kirjoittamisen
mekaaniseen puoleen. Vaikeaa on kirjoittaa sulavasti, ymmärrettävästi -- tyylikkäästikin. Nämä ovat tärkeitä arvoja
myös ohjelmoinnissä.

Tarkoituksenani ei siis ole opettaa lukijaa kirjoittamaan yhtään sellaista ohjelmaa, jota hän ei olisi osannut
kirjoittaa aiemminkin. Toivon kuitenkin, että teksteistä voisi oppia tekniikoita tai vähintäänkin asennetta ohjelmien
jäsentämiseen niin, että niitä olisi miellyttävämpää lukea ja ylläpitää.

=== Varoituksen sana

Pohjana kirjoituksille ovat alunperin https://www.evident.fi/[Evidentin] sisäiseen levitykseen kirjoittamani tekstit.
Koska kohderyhmä on ollut kokenut, erittäin rajallinen ja minulle tuttu, olen ottanut välillä melkoisia hyppyjä
perusteluiden ja selitysten suhteen. Olen tiennyt lukijoiden jakavan osapuilleen samat näkemykset ohjelmoinnista.
Toisaalta olen halunnut jättää tilaa kahvipöytäkeskusteluille. Ei kannata siis niellä kaikkea pureksimatta.

=== Dokumentti verkossa

Nämä tekstit päivittyvät aikojen myötä, mutta viimeisimmät versiot löytyvät seuraavista osoitteista:

- https://komun-koodauskirjoituksia.evident.fi/ (HTML)
- https://komun-koodauskirjoituksia.evident.fi/komun-koodauskirjoituksia.pdf (PDF)

=== Palaute

Risuja, ruusuja ja ideoita kirjoitusaiheista voi lähettää osoitteeseen juha.komulainen@evident.fi.
